apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.appName }}
  labels:
    app: {{ .Values.deployment.appName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector: 
    matchLabels:
      app: {{ .Values.deployment.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
    spec:
      containers:
        - name: {{ .Values.deployment.appName }}
          image: {{ .Values.deployment.image }}
          ports:
            {{- toYaml .Values.deployment.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
