apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-k8s-github-public-component
  labels:
    app: api-k8s-github-public-component
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api-k8s-github-public-component
  template:
    metadata:
      labels:
        app: api-k8s-github-public-component
    spec:
      containers:
        - name: api-k8s-github-public-component
          image: nginx:1.27
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"